### ISSUE TITLE
ToastPosition is not working !

### ISSUE THREAD

**Issue by husamkahlout** [koukibadr/Cherry-Toast#45]
I have attempted to use the example provided in the documentation for the package. However, regardless of whether I set the ToastPosition to 'Position.top' or 'Position.bottom', the toast consistently appears in the center.

![image](https://github.com/koukibadr/Cherry-Toast/assets/45848398/0643df9c-e037-4096-ab6a-7445fe10932b)

**Comment by koukibadr** [comment]
@husamkahlout I just fixed this issue checkout this new version [https://pub.dev/packages/cherry_toast](https://pub.dev/packages/cherry_toast)

**Comment by husamkahlout** [comment]
You did great job , it's fixed , thank you.
