### ISSUE TITLE
Toast without transitions ( Enhancement )

### ISSUE THREAD

**Issue by husamkahlout** [koukibadr/Cherry-Toast#48]
Hello,

I wanted to express my gratitude for the fantastic toast package you've provided. It has been incredibly helpful. I also have a suggestion to potentially enhance this package further. What if we could incorporate an option to display toasts without any transitional animations, such as sliding in from the left or dropping down from the top? Instead, the toast would simply appear at the desired position and disappear with a smooth fade-in and fade-out animation. This could streamline the package and ensure it caters to a wider range of preferences.

Thank you for considering this idea.

**Comment by koukibadr** [comment]
@husamkahlout thanks for this suggestion, yes I think that will enhance the package usage and provide more customization
I will work on it and you can send me your PR also

**Comment by koukibadr** [comment]
@husamkahlout I just published a new version containing this update 
[https://github.com/koukibadr/Cherry-Toast/releases/tag/v1.6.3](https://github.com/koukibadr/Cherry-Toast/releases/tag/v1.6.3)
