### ISSUE TITLE
GPL License 

### ISSUE THREAD

**Issue by jjcazau** [koukibadr/Cherry-Toast#49]
Hi,

You are using the GPL 3 license which means I cannot include this package in my app without releasing my apps source code as per the license agreement. GPL apps are not allowed on the IOS store as Apple requires you own the source, hence GPL apps are rejected. 

https://developer.apple.com/forums/thread/18922

Would it be possible to change the license to MIT or similar so people can use this package in commercial or non-open-source applications?

**Comment by koukibadr** [comment]
Hello @jjcazau a new version has been published contains the MIT license and other updates (version 1.4.3)
