### ISSUE TITLE
Toast height has increased after updating to 1.4.3

### ISSUE THREAD

**Issue by meet2011** [koukibadr/Cherry-Toast#52]
Please see the screenshot.

I'm only displaying description but still the height of a toast is large than previous version. I did no changes from previous to current version. 

I'm facing two issues

1. Previous version had toast position issue but current one is showing larger height, is there any way to reduce it?
2. When I have a two or three lines to show on the toast, it doesn't work either.

```
CherryToast.error(
            title: const Text(""),
            description: Text(message),
            displayTitle: false,
            animationType: AnimationType.fromTop,
            autoDismiss: true,
            displayCloseButton: false,
            borderRadius: 10,
            toastDuration: const Duration(seconds: 2) ,
            animationDuration: const Duration(seconds: 1))
        .show(context);
```

<img width="303" alt="Screenshot 2023-10-02 at 12 44 57 PM" src="https://github.com/koukibadr/Cherry-Toast/assets/12157876/be3b126d-b6fa-4ad6-9536-036b563fc9cb">

**Comment by koukibadr** [comment]
Hello @meet2011 for the first issue the height is now customizable maybe the default height need to be changed but you can set a different height when creating the toast
for the second issue can you provide more info (screenshot, example)

**Comment by meet2011** [comment]
Oh I see I can add height but I want height to be adjusted according to the description. is this possible?

I see I can add height so that long text can be adjusted but description is not known so I'm not sure how I can add height to be dynamic.

Let me have your suggestions

**Comment by koukibadr** [comment]
Yes in my opinion cherry toast should stick to it's design by default while giving the customization to dev also.
I will update the default height, I will let you know once it's published @meet2011.

**Comment by koukibadr** [comment]
I just published a new version [https://pub.dev/packages/cherry_toast](https://pub.dev/packages/cherry_toast)

**Comment by meet2011** [comment]
Looks good!

**Comment by meet2011** [comment]
I'm trying to upgrade to a latest version but it gives me an error. 

Downloaded archive for cherry_toast-1.6.3 had wrong content-hash.

**Comment by koukibadr** [comment]
let me try on my local projects

**Comment by koukibadr** [comment]
@meet2011 try with latest version 1.6.4 just uploaded

**Comment by meet2011** [comment]
v1.6.4 works

Thanks bro!
