### ISSUE TITLE
Clickable background issue 

### ISSUE THREAD

**Issue by sabreys** [koukibadr/Cherry-Toast#57]
Is it possible to make the buttons in the background still clickable while displaying a dialog or overlay in the foreground?

**Comment by koukibadr** [comment]
@sabreys this issue is related to [issue #18](https://github.com/koukibadr/Cherry-Toast/issues/18) and it's fixed with this [PR](https://github.com/koukibadr/Cherry-Toast/pull/47) 
please verify that you are using the latest version of the package
