### ISSUE TITLE
Cherry toast disposed with an Active Ticker

### ISSUE THREAD

**Issue by pagebook1** [koukibadr/Cherry-Toast#67]
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown while finalizing the widget tree:
_CherryToastState#57988(tickers: tracking 1 ticker) was disposed with an active Ticker.
_CherryToastState created a Ticker via its TickerProviderStateMixin, but at the time dispose() was
called on the mixin, that Ticker was still active. All Tickers must be disposed before calling
super.dispose().

sometimes it pops even I showed the Cherry toast once

**Comment by koukibadr** [comment]
@pagebook1 can you provide more info about this bug, package version, flutter version

**Comment by koukibadr** [comment]
I just published a new version fixing this bug 
[https://pub.dev/packages/cherry_toast](https://pub.dev/packages/cherry_toast)

@pagebook1  feel free to close this issue
